---

- name: ZOOKEEPER | User
  import_tasks: user.yml
  tags:
    - zookeeper
    - zookeeper_install
    - zookeeper_user
    - install
    - user

- name: ZOOKEEPER | Install
  import_tasks: install.yml
  tags:
    - zookeeper
    - zookeeper_install
    - install

- name: ZOOKEEPER | Config
  import_tasks: config.yml
  tags:
    - zookeeper
    - zookeeper_config
    - config

- name: ZOOKEEPER | Firewall
  import_tasks: firewall.yml
  tags:
    - zookeeper
    - zookeeper_firewall
    - firewall

- name: ZOOKEEPER | Service
  import_tasks: service.yml
  tags:
    - zookeeper
    - zookeeper_service
    - service
