---
# This is an example playbook to execute Ansible tests.

- name: Verify ZooKeeper installation
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather facts on listening ports
      listen_ports_facts:

    - name: Create list of listening ports
      set_fact:
        tcp_ports: "{{ ansible_facts.tcp_listen | map(attribute='port') | sort | list }}"

    - name: Verify ZooKeeper port is in listening ports
      assert:
        that:
          - 2181 in tcp_ports

    - name: Check that ZooKeeper log file exists
      stat:
        path: /var/log/zookeeper/molecule/zookeeper-zookeeper-server-centos7.log
      register: stat_log_result
      failed_when: not stat_log_result.stat.exists
